name: SKY UX CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - '*.*.*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - uses: blackbaud/skyux-sdk-actions@master
        with:
          browser-stack-access-key: ${{ secrets.BROWSER_STACK_ACCESS_KEY }}
          browser-stack-username: ${{ secrets.BROWSER_STACK_USERNAME }}
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
      - name: Upload coverage report
        run: bash <(curl -s https://codecov.io/bash)
